site_name: Behavior
docs_dir: .

nav:
  - Index: examples/index.md
  - Analog Input: examples/behavior/analog_input/analog_input.md
  - Camera Trigger: examples/behavior/camera_trigger/camera_trigger.md
  - Digital Input: examples/behavior/digital_input/digital_input.md
  - Digital Output: examples/behavior/digital_output/digital_output.md
  - Digital Output Pulse: examples/behavior/digital_output_pulse/digital_output_pulse.md
  - LED Toggle: examples/behavior/led_toggle/led_toggle.md
  - PWM Toggle: examples/behavior/pwm_toggle/pwm_toggle.md
  - Quadrature Encoder: examples/behavior/quadrature_encoder/quadrature_encoder.md
  - Servo Motor Control: examples/behavior/servo_motor_control/servo_motor_control.md
  # _Add additional example markdown files here_